#!/bin/bash
BASEDIR=/var/lib/suckmt                 # base directory for scripts
. ${BASEDIR}/NewsParams

if [ -f ${BASEDIR}/suck.killlog ] ;
then
        cat ${BASEDIR}/suck.killlog >> ${BASEDIR}/KilledNews.log
        rm ${BASEDIR}/suck.killlog
fi
		
if [ -s ${BATCHFILE} ]; 
then	
	# locally post articles
	if [ -s ${BASEDIR}/errors.txt ];
	then
		${BASEDIR}/errors.txt
	fi
    cp ${BATCHFILE} ${BATCHFILE}.delete.these
	echo Doing: ${LOCALPOST} ${LOCALPOST_ARG} ${LOCAL_HOST} ${BATCHFILE} 
	${LOCALPOST} ${LOCALPOST_ARG} ${LOCAL_HOST} ${BATCHFILE} &> ${BASEDIR}/errors.txt
	
	if [ $? -eq 0 ]; 
	then
		echo "Posted Articles Locally"
		echo "Posted Articles Locally" >> ${LOGDIR}/transfer.log
		rm -f `cat ${BATCHFILE}.delete.these` 
	else
		echo "CANT POST ARTICLES: ERROR"
	fi	

    rm -f ${BATCHFILE}.delete.these
else
	# Nothing to do
	echo "CANT POST ARTICLES: NO BATCH FILE"
fi	

rm -f ${LOCKFILE}
echo "  NEWS Process  STOP  `date`" >> ${LOGDIR}/transfer.log
